name: Test and Publish Dart Package
on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (static code check)
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  package:
    name: Publish Dart Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: dart pub get

      - name: Publish pacakge
        run: |
          dart pub publish --dry-run
